### ISSUE TITLE
Folder config

### ISSUE THREAD

**Issue by MakabraBoty** [matijas-05/odrabiamy-bot#18]
Cześć, powiedz mi gdzie umieścić folder config oraz jak dokładnie to uruchomić. Próbowałem kilka razy ale po wpisaniu komendy jaka tam dałeś dodaje się to do docker'a ale bot nie robi się aktywny. Czy ja coś źle robię?

**Comment by matijas-05** [comment]
Cześć, folder config powinien być umieszczony w folderze src. Tak naprawdę to nie spodziewałem się że ktokolwiek będzie tego używał więc to readme tak trochę na szybko zrobiłem.

**Comment by matijas-05** [comment]
Cześć, folder config może być umieszczony w dowolnym miejscu na dysku, później wpiszesz ścieżkę do tego folderu w pliku konfiguracyjnym (jeśli używasz docker compose, jeśli nie to po prostu w komendzie, którą startujesz bota). Dodałem więcej informacji do readme. Jeśli używasz Windowsa to ścieżka [powinna tak wyglądać](https://stackoverflow.com/a/67530166/9854703). Jeśli potrzebujesz więcej pomocy to pisz 😄

**Comment by MakabraBoty** [comment]
Okej, ogarnąłem to już - dzięki. Jest jakiś hosting który mógłby zostawić to uruchomione 24/7 czy docker musi być włączony u mnie lokalnie? Starałem się poszukać czegoś na internecie o tym ale nic nie mogłem znaleźć, mam nadzieję że Ty mi w tym pomożesz 🙂

**Comment by matijas-05** [comment]
Serwery które są wystarczająco mocne aby otworzyć Chrome i przeklikać do odpowiednich podstron (a takie potrzebuje ten bot) są dość drogie, a na dodatek nie mogą być poza Polską bo wtedy odrabiamy.pl wymaga aby captchę rozwiązać. 

Także jeśli chcesz mieć na zawsze bota to polecałbym go postawić na jakimś starym kompie jeśli takiego masz.
Jeśli nie to Google Cloud Compute Engine oferuje 300$ na dwa miesiące za darmo, więc możesz tam wybrać wirtualną maszynę typu e2-standard-4 (126$ miesięcznie, czyli wykorzystasz większość darmowego kredytu przez te 2 miesiące). Tylko pamiętaj aby wybrać serwer, który znajduje się w Polsce.

**Comment by MakabraBoty** [comment]
Okej, mam jeszcze ostatnie pytanie - czy jest potrzebny do tego docker? Pożera on mnóstwo RAMu a myślę że można to odpalić lokalnie nie używając docker'a tylko nie wiem jak 😆

**Comment by matijas-05** [comment]
Nie jest potrzebny, ale jest z dockerem prościej. Jak chcesz lokalnie to zamień 7 linijkę `package.json` na 
```json
"start": "cross-env NODE_ENV=server ts-node --transpile-only src/main.ts",
```
i w `src/main.ts` dodaj pod linijką 19
```typescript
else if (process.env.NODE_ENV === "server") dotenv.config();
```
Musisz jeszcze dodać plik .env do głównego folderu z kodem
```env
TOKEN=
APP_ID=
GUILD_ID=
EMAIL=
PASSWORD=
```
I w folderze `src/config` dodaj plik config.json.
